services:
  pg:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_tracker
    ports:
      - "5440:5432"
    volumes:
      - product_tracker_db_data:/var/lib/postgresql/data
volumes:
  product_tracker_db_data: